/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')

module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      'primary': {
        light: '#67e8f9',
        DEFAULT: '#f53e4f',
        dark: '#0e7490',
      },
      
      white: colors.white,
      blue: colors.blue,
      black: colors.black,
      gray: colors.gray,
      green: colors.green,
      orange: colors.orange,
      emerald: colors.emerald,
      violet: colors.violet,
      indigo: colors.indigo,
      yellow: colors.yellow,
      'grass': '#a5ffdc',
      'fire': '#ffc08b',
      'water': '#a0dcff',
      'bug': '#dafdcb',
      'normal': '#ffeaf7',
      'fairy': '#ffeaf7',
      'flying': '#ffeaf7',
      'poison': '#f6bcff',
      'dragon': '#fff5a3',
      'psychic': '#d5beff',
      'rock': '#d2c8bc',
      'ground': '#ffd175',
      'steel': '#c1dad1',
      'fighting': '#cdb641',
      'ice': '#d1f9ff',
      'electric': '#fff496',
      'ghost': '#ffeffc',
    },
    extend: {},
  },
  safelist: [
    'bg-grass',
    'bg-fire',
    'bg-water',
    'bg-bug',
    'bg-normal',
    'bg-poison',
    'bg-dragon',
    'bg-psychic',
    'bg-rock',
    'bg-ground',
    'bg-steel',
    'bg-fighting',
    'bg-ice',
    'bg-electric',
    'bg-fairy',
    'bg-ghost',
    'bg-flying',
    'text-gray',
  ],
  plugins: [],
}
